global using MediatR;
global using MediatrTest.Application.CQRS.Commands.AddLog;
global using MediatrTest.Application.CQRS.Commands.AddOrUpdateStore;
global using MediatrTest.Common.Interfaces;
global using MediatrTest.Domain.DomainEvents;
global using MediatrTest.Domain.Enums;
global using MediatrTest.Domain.Model;
global using MediatrTest.Domain.Repositories;
global using Microsoft.Extensions.DependencyInjection;
